<a href="https://colab.research.google.com/github/eya-abid/ExData_Plotting1/blob/master/Hello_World_Iris_Flower.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
from sklearn.datasets import load_iris
from sklearn import tree
from sklearn.metrics import f1_score

In [ ]:
iris = load_iris()

In [ ]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [ ]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [ ]:
iris

{'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ===========

In [ ]:
type(iris)

sklearn.utils.Bunch

In [ ]:
type(iris.data)

numpy.ndarray

In [ ]:
type(iris.target)

numpy.ndarray

In [ ]:
iris.data[0]

array([5.1, 3.5, 1.4, 0.2])

In [ ]:
iris.target[0]

0

In [ ]:
test_index = [0,50,100]

In [ ]:
#training data
train_target = np.delete(iris.target,test_index)

In [ ]:
train_data = np.delete(iris.data, test_index, axis=0)

In [ ]:
#testing data
test_target = iris.target[test_index]

In [ ]:
test_data = iris.data[test_index]

In [ ]:
#classifier
clf = tree.DecisionTreeClassifier()

In [ ]:
clf.fit(train_data, train_target)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
#expected result
test_target

array([0, 1, 2])

In [ ]:
#predicted result
preds = clf.predict(test_data)
preds

array([0, 1, 2])

In [ ]:
#TADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA !

In [ ]:
#Printing the model's accuracy
f1_score(preds,test_target,average="weighted")

1.0

In [ ]:
#Visualization of decision tree

In [ ]:
#export decision tree into a dot file
tree.export_graphviz(clf,out_file='MyDecisionTree2.dot', feature_names=iris.feature_names, class_names=iris.target_names, filled=True, rounded=True, impurity=False) 

In [ ]:
#just convert the dot file into png or pdf and open it

In [ ]:
from subprocess import check_call
check_call(['dot','-Tpng','MyDecisionTree2.dot','-o','IrisFlowers.png'])

0